### ISSUE TITLE
Can't find provider with id `EditConfig` .

### ISSUE THREAD

**Issue by haavamoa** [Illedan/OpenRepo#5]
![image](https://user-images.githubusercontent.com/2527084/65483601-1a100500-de9d-11e9-8474-78ac926776ad.png)

Version: `0.0.8`

I guess that this bug was introduced when you removed the unessesary EditConfig` value in the configuration.

This is my config:
```
# Welcome to OpenRepo
# Created by https://github.com/Illedan 
EditConfig:
    none

Local:
    <my-path>
```

**Comment by Illedan** [comment]
To fix it on your side, simply remove the `EditConfig:` line + the `none` line.
I will add a guard to this particular case.
