### ISSUE TITLE
Configuration does not support paths with spaces

### ISSUE THREAD

**Issue by Yazurka** [Illedan/OpenRepo#6]
Local:
    C:\Users\User1\source\repos

Personal:
    reposTerminal C:\Users\User1\Desktop\testcommand.bat => works
    reposTerminal2 C:\Users\User1\Desktop\Test Folder\testcommand.bat => dont work

**Comment by Illedan** [comment]
Thx for reporting.
This is fixed in the 0.0.10 version.
You can now specify paths with spaces if the whole path is wrapped in quotes ( " )
